#pragma once

#include "raylib.h"

struct Collision {
    float angle;//deg
    float hit_distance;
};

struct Border {
    Vector2 start;
    Vector2 end;
};

constexpr int COLLISION_COUNT {8};

constexpr float COLLISIONS_ANGLE[COLLISION_COUNT] {0.0f,90.0f,180.0f,270.0f,45.0f,135.0f,225.0f,315.0f};

constexpr int COLLISION_DISTANCE {50 * 2};

constexpr int SCREEN_WIDTH = 1000;
constexpr int SCREEN_HEIGHT = 900;

constexpr int ROAD_WIDTH {150};

constexpr int SPAWN_SIZE = ROAD_WIDTH * 0.6f;

constexpr int SPAWN_SIZE_DIFF = ROAD_WIDTH * 0.1f;

constexpr int ROADS_GAP {ROAD_WIDTH};

constexpr float CAR_WIDTH {50.0f};

constexpr float CAR_HEIGHT {20.0f};

constexpr Rectangle city_roads[] {
    {ROADS_GAP,0,ROAD_WIDTH,SCREEN_HEIGHT},

    {SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,0,ROAD_WIDTH,SCREEN_HEIGHT},


    {0,ROADS_GAP,SCREEN_WIDTH,ROAD_WIDTH},

    {0,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH,SCREEN_WIDTH,ROAD_WIDTH},
};

constexpr Border road_borders[] {
    //vertical borders
    {{ROADS_GAP,0},{ROADS_GAP,ROADS_GAP}},
    {{ROADS_GAP + ROAD_WIDTH,0},{ROADS_GAP + ROAD_WIDTH,ROADS_GAP}},

    {{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,0},{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,ROADS_GAP}},
    {{SCREEN_WIDTH - ROADS_GAP,0},{SCREEN_WIDTH - ROADS_GAP,ROADS_GAP}},

    {{ROADS_GAP,SCREEN_HEIGHT - ROADS_GAP},{ROADS_GAP,SCREEN_HEIGHT}},
    {{ROADS_GAP + ROAD_WIDTH,SCREEN_HEIGHT - ROADS_GAP},{ROADS_GAP + ROAD_WIDTH,SCREEN_HEIGHT}},

    {{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,SCREEN_HEIGHT - ROADS_GAP},{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,SCREEN_HEIGHT}},
    {{SCREEN_WIDTH - ROADS_GAP,SCREEN_HEIGHT - ROADS_GAP},{SCREEN_WIDTH - ROADS_GAP,SCREEN_HEIGHT}},

    {{ROADS_GAP,ROADS_GAP + ROAD_WIDTH},{ROADS_GAP,ROADS_GAP + ROAD_WIDTH + SCREEN_HEIGHT - ROADS_GAP * 2 - ROAD_WIDTH * 2}},
    {{ROADS_GAP + ROAD_WIDTH ,ROADS_GAP + ROAD_WIDTH},{ROADS_GAP + ROAD_WIDTH,ROADS_GAP + ROAD_WIDTH + SCREEN_HEIGHT - ROADS_GAP * 2 - ROAD_WIDTH * 2}},

    {{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,ROADS_GAP + ROAD_WIDTH},{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,ROADS_GAP + ROAD_WIDTH + SCREEN_HEIGHT - ROADS_GAP * 2 - ROAD_WIDTH * 2}},
    {{SCREEN_WIDTH - ROADS_GAP ,ROADS_GAP + ROAD_WIDTH},{SCREEN_WIDTH - ROADS_GAP,ROADS_GAP + ROAD_WIDTH + SCREEN_HEIGHT - ROADS_GAP * 2 - ROAD_WIDTH * 2}},

    {{0,ROADS_GAP},{0,ROADS_GAP + ROAD_WIDTH}},
    {{0,SCREEN_HEIGHT - ROADS_GAP},{0,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH}},

    {{SCREEN_WIDTH,ROADS_GAP},{SCREEN_WIDTH,ROADS_GAP + ROAD_WIDTH}},
    {{SCREEN_WIDTH,SCREEN_HEIGHT - ROADS_GAP},{SCREEN_WIDTH,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH}},

    //horizontal borders
    {{0,ROADS_GAP},{ROADS_GAP,ROADS_GAP}},
    {{0,ROADS_GAP + ROAD_WIDTH},{ROADS_GAP,ROADS_GAP + ROAD_WIDTH}},

    {{SCREEN_WIDTH - ROADS_GAP,ROADS_GAP},{SCREEN_WIDTH,ROADS_GAP}},
    {{SCREEN_WIDTH - ROADS_GAP,ROADS_GAP + ROAD_WIDTH},{SCREEN_WIDTH,ROADS_GAP + ROAD_WIDTH}},

    {{SCREEN_WIDTH - ROADS_GAP,SCREEN_HEIGHT - ROADS_GAP },{SCREEN_WIDTH,SCREEN_HEIGHT - ROADS_GAP}},

    {{SCREEN_WIDTH - ROADS_GAP,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH},{SCREEN_WIDTH,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH }},

    {{0,SCREEN_HEIGHT - ROADS_GAP},{ROADS_GAP,SCREEN_HEIGHT - ROADS_GAP}},
    {{0,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH },{ROADS_GAP,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH}},

    {{ROADS_GAP + ROAD_WIDTH,ROADS_GAP},{ROADS_GAP + ROAD_WIDTH + SCREEN_WIDTH - ROADS_GAP * 2 - ROAD_WIDTH * 2,ROADS_GAP}},
    {{ROADS_GAP + ROAD_WIDTH,ROADS_GAP + ROAD_WIDTH},{ROADS_GAP + ROAD_WIDTH + SCREEN_WIDTH - ROADS_GAP * 2 - ROAD_WIDTH * 2,ROADS_GAP + ROAD_WIDTH}},

    {{ROADS_GAP + ROAD_WIDTH,SCREEN_HEIGHT - ROADS_GAP},{ROADS_GAP + ROAD_WIDTH + SCREEN_WIDTH - ROADS_GAP * 2 - ROAD_WIDTH * 2,SCREEN_HEIGHT - ROADS_GAP}},
    {{ROADS_GAP + ROAD_WIDTH,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH},{ROADS_GAP + ROAD_WIDTH + SCREEN_WIDTH - ROADS_GAP * 2 - ROAD_WIDTH * 2,SCREEN_HEIGHT - ROADS_GAP - ROAD_WIDTH}},

    {{ROADS_GAP,0 },{ROADS_GAP + ROAD_WIDTH,0}},
    {{SCREEN_WIDTH - ROADS_GAP,0 },{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,0}},

    {{ROADS_GAP,SCREEN_HEIGHT},{ROADS_GAP + ROAD_WIDTH,SCREEN_HEIGHT}},
    {{SCREEN_WIDTH - ROADS_GAP,SCREEN_HEIGHT },{SCREEN_WIDTH - ROADS_GAP - ROAD_WIDTH,SCREEN_HEIGHT}},
};

constexpr Rectangle spawn_points[] {
    {city_roads[0].x + (ROAD_WIDTH - SPAWN_SIZE) / 2,city_roads[0].y + SPAWN_SIZE_DIFF,SPAWN_SIZE,SPAWN_SIZE},
    {city_roads[0].x + (ROAD_WIDTH - SPAWN_SIZE) / 2,city_roads[0].y + city_roads[0].height - SPAWN_SIZE - SPAWN_SIZE_DIFF,SPAWN_SIZE,SPAWN_SIZE},

    {city_roads[1].x + (ROAD_WIDTH - SPAWN_SIZE) / 2,city_roads[1].y + SPAWN_SIZE_DIFF,SPAWN_SIZE,SPAWN_SIZE},
    {city_roads[1].x + (ROAD_WIDTH - SPAWN_SIZE) / 2,city_roads[1].y + city_roads[1].height - SPAWN_SIZE - SPAWN_SIZE_DIFF,SPAWN_SIZE,SPAWN_SIZE},

    {city_roads[2].x + SPAWN_SIZE_DIFF,city_roads[2].y + (ROAD_WIDTH - SPAWN_SIZE) / 2,SPAWN_SIZE,SPAWN_SIZE},
    {city_roads[2].x + city_roads[2].width - SPAWN_SIZE - SPAWN_SIZE_DIFF,city_roads[2].y + (ROAD_WIDTH - SPAWN_SIZE) / 2,SPAWN_SIZE,SPAWN_SIZE},

    {city_roads[3].x + SPAWN_SIZE_DIFF,city_roads[3].y + (ROAD_WIDTH - SPAWN_SIZE) / 2,SPAWN_SIZE,SPAWN_SIZE},
    {city_roads[3].x + city_roads[3].width - SPAWN_SIZE - SPAWN_SIZE_DIFF,city_roads[3].y + (ROAD_WIDTH - SPAWN_SIZE) / 2,SPAWN_SIZE,SPAWN_SIZE},
};